### ISSUE TITLE
일부 블루투스 이어폰 사용 시  IO관련 에러 발생

### ISSUE THREAD

**Issue by hagukin** [hagukin/Geophyte#16]
FATAL ERROR::an error occurred during running SoundThread - [Errno -9998] Invalid number of channels
Traceback (most recent call last):
  File "E:\내 폴더\게임제작\Geophyte\Geophyte_alpha\src\sound.py", line 44, in run
    super().run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\내 폴더\게임제작\Geophyte\Geophyte_alpha\src\sound.py", line 370, in play_sound
    stream = self.p.open(format=self.p.get_format_from_width(f.getsampwidth()),
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)

**Comment by hagukin** [comment]
https://stackoverflow.com/questions/31073667/getting-ioerror-errno-invalid-number-of-channels-9998-when-using-mic-with-py
https://stackoverflow.com/questions/58613948/what-does-the-number-of-channels-mean-in-pyaudio
channel을 1로 바꾸면 해결될 듯 함.

**Comment by hagukin** [comment]
> https://stackoverflow.com/questions/31073667/getting-ioerror-errno-invalid-number-of-channels-9998-when-using-mic-with-py https://stackoverflow.com/questions/58613948/what-does-the-number-of-channels-mean-in-pyaudio channel을 1로 바꾸면 해결될 듯 함.

1로 설정 시 소리가 들리긴 하나 소리가 훨씬 낮게 들림
